gridfsfiles/config/routes.rb
Rails.application.routes.draw do
  root to: 'grid_fs_files#index'
  resources :grid_fs_files
  get '/grid_fs_files/contents/:id/', to: 'grid_fs_files#contents', as: 'contents'

end

gridfsfiles/app/models/grid_fs_file.rb
class GridFsFile
  include ActiveModel::Model
  attr_accessor :contentType, :filename, :author, :topic
  attr_writer :contents
  attr_reader :id, :uploadDate, :chunkSize, :length, :md5

  def initialize(params={})
    Rails.logger.debug {"instantiating GridFsFile #{params}"}
    if params[:_id]  #hash came from GridFS
      @id=params[:_id].to_s
      @author=params[:metadata].nil? ? nil : params[:metadata][:author]
      @topic=params[:metadata].nil? ? nil : params[:metadata][:topic]
    else              #assume hash came from Rails
      @id=params[:id]
      @author=params[:author]
      @topic=params[:topic]
    end
    @chunkSize=params[:chunkSize]
    @uploadDate=params[:uploadDate]
    @contentType=params[:contentType]
    @filename=params[:filename]
    @length=params[:length]
    @md5=params[:md5]
    @contents=params[:contents]
    Rails.logger.debug {"instantiated GridFsFile #{self}"}
  end

  def persisted?
    !@id.nil?
  end
  def created_at
    nil
  end
  def updated_at
    nil
  end
  
  def self.mongo_client
    @@db ||= Mongoid::Clients.default
  end

  def self.id_criteria id
    {_id:BSON::ObjectId.from_string(id)}
  end
  def id_criteria
    self.class.id_criteria @id
  end

  def self.all
    files=[]
    mongo_client.database.fs.find.each do |r| 
      files << GridFsFile.new(r)
    end
    return files
  end

  def self.find id
    f=mongo_client.database.fs.find(id_criteria(id)).first
    return f.nil? ? nil : GridFsFile.new(f)
  end

  def contents
    Rails.logger.debug {"getting gridfs content #{@id}"}
    f=self.class.mongo_client.database.fs.find_one(id_criteria)
    if f 
      buffer = ""
      f.chunks.reduce([]) do |x,chunk| 
          buffer << chunk.data.data 
      end
      return buffer
    end 
  end
  
  def save
    Rails.logger.debug {"saving gridfs file #{self.to_s}"}
    description = {}
    description[:filename]=@filename          if !@filename.nil?
    description[:content_type]=@contentType   if !@contentType.nil?
    if @author || @topic
      description[:metadata] = {}
      description[:metadata][:author]=@author  if !@author.nil?
      description[:metadata][:topic]=@topic    if !@topic.nil?
    end

    if @contents
      Rails.logger.debug {"contents= #{@contents}"}
      grid_file = Mongo::Grid::File.new(@contents.read, description )
      id=self.class.mongo_client.database.fs.insert_one(grid_file)
      @id=id.to_s
      Rails.logger.debug {"saved gridfs file #{id}"}
      @id
    end
  end

  def update params
    #TODO
  end

  def destroy
    Rails.logger.debug {"destroying gridfs file #{@id}"}
    self.class.mongo_client.database.fs.find(id_criteria).delete_one
  end
end

gridfsfiles/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

gridfsfiles/app/controllers/grid_fs_files_controller.rb
class GridFsFilesController < ApplicationController
  before_action :set_grid_fs_file, only: [:show, :edit, :update, :destroy, :contents]

  def contents
    send_data @grid_fs_file.contents, 
              {filename: @grid_fs_file.filename, type: @grid_fs_file.contentType, disposition: 'inline'}
  end

  # GET /grid_fs_files
  # GET /grid_fs_files.json
  def index
    @grid_fs_files = GridFsFile.all
  end

  # GET /grid_fs_files/1
  # GET /grid_fs_files/1.json
  def show
  end

  # GET /grid_fs_files/new
  def new
    @grid_fs_file = GridFsFile.new
  end

  # GET /grid_fs_files/1/edit
  def edit
  end

  # POST /grid_fs_files
  # POST /grid_fs_files.json
  def create
    @grid_fs_file = GridFsFile.new(grid_fs_file_params)

    respond_to do |format|
      if @grid_fs_file.save
        format.html { redirect_to @grid_fs_file, notice: 'Grid fs file was successfully created.' }
        format.json { render :show, status: :created, location: @grid_fs_file }
      else
        format.html { render :new }
        format.json { render json: @grid_fs_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grid_fs_files/1
  # PATCH/PUT /grid_fs_files/1.json
  def update
    respond_to do |format|
      if @grid_fs_file.update(grid_fs_file_params)
        format.html { redirect_to @grid_fs_file, notice: 'Grid fs file was successfully updated.' }
        format.json { render :show, status: :ok, location: @grid_fs_file }
      else
        format.html { render :edit }
        format.json { render json: @grid_fs_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grid_fs_files/1
  # DELETE /grid_fs_files/1.json
  def destroy
    @grid_fs_file.destroy
    respond_to do |format|
      format.html { redirect_to grid_fs_files_url, notice: 'Grid fs file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grid_fs_file
      @grid_fs_file = GridFsFile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grid_fs_file_params
      params.require(:grid_fs_file).permit(:filename, :contentType, :author, :topic, :uploadDate, :length, :chunkSize, :md5, :contents)
    end
end

gridfsfiles/app/helpers/application_helper.rb
module ApplicationHelper
end

gridfsfiles/app/helpers/grid_fs_files_helper.rb
module GridFsFilesHelper
end

gridfsfiles/app/views/grid_fs_files/_form.html.erb
<%= form_for(@grid_fs_file) do |f| %>
  <% if @grid_fs_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grid_fs_file.errors.count, "error") %> prohibited this grid_fs_file from being saved:</h2>

      <ul>
      <% @grid_fs_file.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :filename %><br>
    <%= f.text_field :filename %>
  </div>
  <div class="field">
    <%= f.label :contentType %><br>
    <%= f.text_field :contentType %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :topic %><br>
    <%= f.text_field :topic %>
  </div>
  <div class="field">
    <%= f.label :uploadDate %><br>
    <%= f.text_field :uploadDate, :readonly => true %>
  </div>
  <div class="field">
    <%= f.label :length %><br>
    <%= f.number_field :length, :readonly => true %>
  </div>
  <div class="field">
    <%= f.label :chunkSize %><br>
    <%= f.number_field :chunkSize, :readonly => true %>
  </div>
  <div class="field">
    <%= f.label :md5 %><br>
    <%= f.text_field :md5, :readonly => true %>
  </div>
  <div class="field">
    <%= f.label :contents %><br>
    <%= f.file_field :contents %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

gridfsfiles/app/views/grid_fs_files/edit.html.erb
<h1>Editing Grid Fs File</h1>

<%= render 'form' %>

<%= link_to 'Show', @grid_fs_file %> |
<%= link_to 'Back', grid_fs_files_path %>

gridfsfiles/app/views/grid_fs_files/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Grid Fs Files</h1>

<table>
  <thead>
    <tr>
      <th>Contents</th>
      <th>Filename</th>
      <th>Contenttype</th>
      <th>Author</th>
      <th>Topic</th>
      <th>Uploaddate</th>
      <th>Length</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grid_fs_files.each do |grid_fs_file| %>
      <tr>
        <td><img height="100px" width="130px" src= <%= contents_path("#{grid_fs_file.id}")%>/></td>
        <td><%= grid_fs_file.filename %></td>
        <td><%= grid_fs_file.contentType %></td>
        <td><%= grid_fs_file.author %></td>
        <td><%= grid_fs_file.topic %></td>
        <td><%= grid_fs_file.uploadDate %></td>
        <td><%= grid_fs_file.length %></td>
        <td><%= link_to 'Show', grid_fs_file %></td>
        <td><%= link_to 'Edit', edit_grid_fs_file_path(grid_fs_file) %></td>
        <td><%= link_to 'Destroy', grid_fs_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grid fs file', new_grid_fs_file_path %>

gridfsfiles/app/views/grid_fs_files/new.html.erb
<h1>New Grid Fs File</h1>

<%= render 'form' %>

<%= link_to 'Back', grid_fs_files_path %>

gridfsfiles/app/views/grid_fs_files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Filename:</strong>
  <%= @grid_fs_file.filename %>
</p>

<p>
  <strong>Contenttype:</strong>
  <%= @grid_fs_file.contentType %>
</p>

<p>
  <strong>Author:</strong>
  <%= @grid_fs_file.author %>
</p>

<p>
  <strong>Topic:</strong>
  <%= @grid_fs_file.topic %>
</p>

<p>
  <strong>Uploaddate:</strong>
  <%= @grid_fs_file.uploadDate %>
</p>

<p>
  <strong>Length:</strong>
  <%= @grid_fs_file.length %>
</p>

<p>
  <strong>Chunksize:</strong>
  <%= @grid_fs_file.chunkSize %>
</p>

<p>
  <strong>Md5:</strong>
  <%= @grid_fs_file.md5 %>
</p>

<p>
  <strong>Contents:</strong>
  <img height="500px" width="650px" src= <%= contents_path("#{@grid_fs_file.id}")%>/>
</p>

<%= link_to 'Edit', edit_grid_fs_file_path(@grid_fs_file) %> |
<%= link_to 'Back', grid_fs_files_path %>

gridfsfiles/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gridfsfiles</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>